import {useMemo,useState} from 'react';import{NavLink,Route,Routes,Link}from'react-router-dom';import{CalendarDays,Compass,Map as MapIcon,Utensils,Sparkles,Clock3,ChevronRight,Heart,Check,Shuffle,Sun,Waves,Camera,MapPin,Timer}from'lucide-react';import{MapContainer,TileLayer,Marker,Popup}from'react-leaflet';import L from'leaflet';import'leaflet/dist/leaflet.css';import{useLocalStorage}from'./useLocalStorage';
type Day={date:string;title:string;subtitle:string;stops:string[];vibe:string;color:string};
const days:Day[]=[
{date:'Tue, Oct 27',title:'Arrive + exhale',subtitle:'Easy arrival, sunset and dinner',vibe:'Slow start',color:'Arrival',stops:['CUN 12:00 PM','Resort check-in','Pool / beach','Sunset','Dinner']},
{date:'Wed, Oct 28',title:'Lagoon + Maya',subtitle:'Sian Ka’an • Muyil • Mayan canal',vibe:'Adventure',color:'Water',stops:['Breakfast','Sian Ka’an','Muyil ruins','Mayan canal','Dinner']},
{date:'Thu, Oct 29',title:'Coba + cenote + beach',subtitle:'Jungle history, water and sand',vibe:'Explore',color:'Culture',stops:['Breakfast','Coba','Cave / open cenote','Playa Paraíso','Sunset']},
{date:'Fri, Oct 30',title:'Tulum your way',subtitle:'Pueblo, markets, beach zone and night',vibe:'Local life',color:'Local',stops:['Breakfast','Tulum Pueblo','Local market','Beach zone','Dinner + evening']},
{date:'Sat, Oct 31',title:'Slow day',subtitle:'Spa, pool, beach and Halloween',vibe:'Wellness',color:'Relax',stops:['Sleep in','Spa / massage','Pool / beach','Sunset','Halloween evening']},
{date:'Sun, Nov 1',title:'Hasta luego',subtitle:'Breakfast, check-out and CUN',vibe:'Departure',color:'Travel',stops:['Breakfast','Check-out','CUN 11:30 AM']}];
const places=[['Sian Ka’an','Water','Muyil',19.42,-87.75],['Muyil','Culture','Muyil',19.414,-87.60],['Coba','Culture','Coba',20.495,-87.736],['Playa Paraíso','Beach','Tulum',20.209,-87.43],['Tulum Pueblo','Local','Tulum',20.211,-87.465],['Beach Zone','Beach','Tulum',20.18,-87.49]] as const;
const foods=[['Fresco’s','Mexican • Seafood','Beach',['Beachfront','Vegetarian','Vegan','Healthy'],true,true,'Beach-area dining at Km 7 with vegetarian and vegan options.'],['Sun Love Cafe','Plant-based','Beach',['Vegan','Vegetarian','Beachfront','Cafe','Healthy'],true,true,'Beachfront plant-based café at Ahau, ideal for a relaxed breakfast or lunch.'],['Il Bacaro Tulum','Italian','Pueblo',['Italian','Romantic','Dinner'],true,false,'Relaxed Italian trattoria in Centro with homemade pasta and pizza.'],['La Hoja Verde','Vegan • Mexican','Pueblo',['Vegan','Vegetarian','Mexican','Healthy','Local'],true,true,'Plant-based Mexican and international food in central Tulum.'],['Suculenta Tulum','Mexican • Vegetarian','Pueblo',['Vegan','Vegetarian','Mexican','Local','Healthy'],true,true,'Plant-forward Mexican spot known for tamales and traditional-inspired dishes.'],['Pizzeria Checkpoint Ciao','Italian • Pizza','Beach',['Italian','Beachfront','Cocktails','Dinner','Vegetarian'],true,false,'Neapolitan pizza, pasta and Italian wines on the beach road.'],['The Real Coconut','Plant-forward','Beach',['Vegan','Vegetarian','Healthy','Beachfront'],true,true,'Wellness-focused restaurant with plant-forward choices near the beach.']];